version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: mchlobinna83/vprofiledb
    container_image: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    images: memcached
    ports:
      - "11211:11211"

  vpromq01:
    images: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBIT_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: mchlobinna83/vprofileapp
    container_image: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/var/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: mchlobinna83/vprofileweb
    container_image: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata:{}
  vproappdata:{}